/**
 * Sanitizes markdown formatted text into clean spoken text for TTS engines (Deepgram, SpeechSynthesis, etc.)
 * Strips asterisks (*), hashtags (#), backticks (`), bullet points, blockquotes, markdown links, and raw code/JSON blocks.
 *
 * @param {string} text - Raw markdown text generated by LLM
 * @returns {string} Clean, plain text suitable for speech audio generation
 */
export function cleanTextForSpeech(text) {
  if (!text || typeof text !== 'string') return '';

  let cleaned = text;

  // 1. Handle JSON action confirmation blocks
  cleaned = cleaned.replace(/```json[\s\S]*?```/gi, (match) => {
    if (match.includes('ACTION_CONFIRMATION')) {
      return ' Action confirmation required. ';
    }
    return '';
  });

  // 2. Remove remaining code blocks
  cleaned = cleaned.replace(/```[\s\S]*?```/g, ' Code snippet omitted. ');

  // 3. Remove headers (# Header, ## Subheader)
  cleaned = cleaned.replace(/^#+\s+/gm, '');

  // 4. Remove bold, italic, strikethrough markdown
  cleaned = cleaned.replace(/\*\*([^*]+)\*\*/g, '$1');
  cleaned = cleaned.replace(/\*([^*]+)\*/g, '$1');
  cleaned = cleaned.replace(/__([^_]+)__/g, '$1');
  cleaned = cleaned.replace(/_([^_]+)_/g, '$1');
  cleaned = cleaned.replace(/~~([^~]+)~~/g, '$1');

  // 5. Remove markdown links [Text](url) -> Text
  cleaned = cleaned.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');

  // 6. Remove inline code backticks `code` -> code
  cleaned = cleaned.replace(/`([^`]+)`/g, '$1');

  // 7. Remove list bullets (- item, * item, + item)
  cleaned = cleaned.replace(/^\s*[-*+]\s+/gm, '');

  // 8. Clean up numbered lists (1. item -> item)
  cleaned = cleaned.replace(/^\s*\d+\.\s+/gm, '');

  // 9. Remove blockquotes (> text)
  cleaned = cleaned.replace(/^\s*>\s+/gm, '');

  // 10. Clean markdown tables (remove |---|---| lines and replace | with pauses/commas)
  cleaned = cleaned.replace(/^\s*\|.*\|\s*$/gm, (line) => {
    if (line.includes('---')) return '';
    return line.split('|').filter(cell => cell.trim()).join(', ');
  });

  // 11. Remove horizontal rules (---, ***, ___)
  cleaned = cleaned.replace(/^\s*[-*_]{3,}\s*$/gm, '');

  // 12. Strip remaining standalone formatting symbols (*, #, `, ~, _)
  cleaned = cleaned.replace(/[*#`~]/g, '');

  // 13. Replace newlines with periods or spaces for natural TTS pauses
  cleaned = cleaned.replace(/\r?\n/g, '. ');

  // 14. Normalize whitespace and clean up double periods or punctuation artifacts
  cleaned = cleaned.replace(/\s+/g, ' ');
  cleaned = cleaned.replace(/\.\s*\./g, '.');

  return cleaned.trim();
}
